### ISSUE TITLE
Pastas dos membros do time

### ISSUE THREAD

**Issue by eheredia42** [SENAC-2023-1-TSI-PI-Pagina-Web-Dinamica/SENAC-2023-1-TSI-PI-2-Grupo-E3#1]
As pastas dos membros do time devem estar na raiz do repositório e não em uma pasta!

Corrijam esta situação.

**Comment by ElvisCostaOliveira** [comment]
Feito os ajustes solicitados, utilizando o exemplo informado no classroom.
