### ISSUE TITLE
Nomeação do arquivo DIARIO.md

### ISSUE THREAD

**Issue by eheredia42** [SENAC-2023-1-TSI-PI-Pagina-Web-Dinamica/SENAC-2023-1-TSI-PI-2-Grupo-E3#3]
Verifiquem o arquivo diário em suas pastas pessoais. 

Eles devem ser nomeados como DIARIO.md

**Comment by ElvisCostaOliveira** [comment]
Arquivos renomeados para DIARIO.md conforme solicitado.
